# Generated by Django 4.2.4 on 2024-01-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_member_joined_date_member_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numbers", models.CharField(max_length=255)),
            ],
        ),
    ]
