# Generated by Django 4.2.4 on 2024-01-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0006_user_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_information",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
