# Generated by Django 4.1.12 on 2024-02-01 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0008_ticket"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ticket",
        ),
    ]
