# Generated by Django 4.1.12 on 2024-02-01 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0011_test"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="test",
            new_name="Tickets",
        ),
    ]
