# Generated by Django 4.1.12 on 2024-02-01 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0012_rename_test_tickets"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TicketCounter",
        ),
    ]
