# Generated by Django 4.1.12 on 2024-02-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0013_delete_ticketcounter"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
            ],
        ),
    ]
